<?php
/**
 *
 * Here is where all the admin field data is stored
 * All the data is stored in arrays and then looped though
 * @author AppThemes
 * @version 1.0
  *
 * Array param definitions are as follows:
 * name    = field name
 * desc    = field description
 * tip     = question mark tooltip text
 * id      = database column name or the WP meta field name
 * css     = any on-the-fly styles you want to add to that field
 * type    = type of html field
 * req     = if the field is required or not (1=required)
 * min     = minimum number of characters allowed before saving data
 * std     = default value. not being used
 * js      = allows you to pass in javascript for onchange type events
 * vis     = if field should be visible or not. used for dropdown values field
 * visid   = this is the row css id that must correspond with the dropdown value that controls this field
 * options = array of drop-down option value/name combo
 * altclass = adds a new css class to the input field
 *
 *
 */

global $app_abbr;

$options_settings = array(


    array(  'type' => 'tab',
            'tabname' => __( 'General', APP_TD ),
            'id' => '0' ),

            array(	'name' => __( 'Site Configuration', APP_TD ),
                    'type' => 'title',
                    'desc' => '',
                    'id' => ''),

                array(  'name' => __( 'Color Scheme', APP_TD ),
                        'desc' => '',
                        'tip' => __( 'Select the color scheme you would like to use.', APP_TD ),
                        'id' => $app_abbr.'_stylesheet',
                        'css' => 'min-width:230px;',
                        'std' => 'red',
                        'vis' => '',
                        'req' => '',
                        'js' => '',
                        'min' => '',
                        'type' => 'select',
                        'options' => array( 'red.css' => __( 'Red Theme', APP_TD ),
                                            'blue.css' => __( 'Blue Theme', APP_TD ),
                                            'orange.css' => __( 'Orange Theme', APP_TD ),
                                            'green.css' => __( 'Green Theme', APP_TD ),
                                            'gray.css' => __( 'Gray Theme', APP_TD )
                                            )),


                array(  'name' => __( 'Enable Logo', APP_TD ),
                        'desc' => '',
                        'tip' => __( 'If you do not have a logo to use, select no and this will display the title and description of your web site instead.', APP_TD ),
                        'id' => $app_abbr.'_use_logo',
                        'css' => 'min-width:100px;',
                        'std' => 'yes',
                        'vis' => '',
                        'req' => '',
                        'js' => '',
                        'min' => '',
                        'type' => 'select',
                        'options' => array(  'yes' => __( 'Yes', APP_TD ),
                                             'no'  => __( 'No', APP_TD ) )),

                array(  'name' => __( 'Web Site Logo', APP_TD ),
                        'desc' => __( 'Upload a logo or paste an image URL directly.', APP_TD ),
                        'tip' => __( 'Paste the URL of your web site logo image here. It will replace the default header logo.(i.e. http://www.yoursite.com/logo.jpg)', APP_TD ),
                        'id' => $app_abbr.'_logo_url',
                        'css' => 'min-width:398px;',
                        'vis' => '',
                        'req' => '',
                        'min' => '',
                        'type' => 'upload',
                        'std' => ''),

				        array(  'name' => __( 'Web Site Favicon', APP_TD ),
                        'desc' => sprintf( __( '<a target="_new" href="%s">Create your own</a> favicon or paste an image URL directly. Must be a 16x16 .ico file.', APP_TD ), 'http://www.favicon.cc/' ),
                        'tip' => __( 'Paste the URL of your web site favicon image here. It will replace the default favicon logo.(i.e. http://www.yoursite.com/favicon.ico)', APP_TD ),
                        'id' => $app_abbr.'_favicon_url',
                        'css' => 'min-width:398px;',
                        'vis' => '',
                        'req' => '',
                        'min' => '',
                        'type' => 'upload',
                        'std' => ''),

                array(  'name' => __( 'Feedburner URL', APP_TD ),
                        'desc' => sprintf( '%s' . __( "Sign up for a free <a target='_new' href='%s'>Feedburner account</a>.", APP_TD ), '<div class="feedburnerico"></div>', 'http://feedburner.google.com' ),
                        'tip' => __( 'Paste your Feedburner address here. It will automatically redirect your default RSS feed to Feedburner. You must have a Google Feedburner account setup first.', APP_TD ),
                        'id' => $app_abbr.'_feedburner_url',
                        'css' => 'min-width:500px;',
                        'vis' => '',
                        'req' => '',
                        'min' => '',
                        'type' => 'text',
                        'std' => ''),


                array(  'name' => __( 'Twitter ID', APP_TD ),
                        'desc' => sprintf( '%s' . __( "Sign up for a free <a target='_new' href='%s'>Twitter account</a>.", APP_TD ), '<div class="twitterico"></div>', 'http://twitter.com' ),
                        'tip' => __( 'Paste your Twitter ID here. It will be used in the Twitter sidebar widget. You must have a Twitter account setup first.', APP_TD ),
                        'id' => $app_abbr.'_twitter_id',
                        'css' => 'min-width:500px;',
                        'vis' => '',
                        'req' => '',
                        'min' => '',
                        'type' => 'text',
                        'std' => ''),

                array(  'name' => __( 'Facebook Page ID', APP_TD ),
                        'desc' => sprintf( '%s' . __( "Sign up for a free <a target='_new' href='%s'>Facebook account</a>.", APP_TD ), '<div class="facebookico"></div>', 'http://www.facebook.com' ),
                        'tip' => __( 'Paste your Facebook Page ID or username here. It will display Facebook icon with URL to you page in the top bar. You must have a Facebook account and page setup first.', APP_TD ),
                        'id' => $app_abbr.'_facebook_id',
                        'css' => 'min-width:500px;',
                        'vis' => '',
                        'req' => '',
                        'min' => '',
                        'type' => 'text',
                        'std' => ''),

				/* Currently Disabled
                array(  'name' => __( 'ShareThis ID', APP_TD ),
                        'desc' => sprintf( '%s' . __( "Sign up for a free <a target='_new' href='%s'>ShareThis account</a>.", APP_TD ), '<div class="sharethisico"></div>', 'http://sharethis.com' ),
                        'tip' => __( 'Paste your ShareThis publisher ID here. It will show the ShareThis buttons on the blog post and job listings. You must have a ShareThis account and page setup first.', APP_TD ),
                        'id' => $app_abbr.'_sharethis_id',
                        'css' => 'min-width:500px;',
                        'vis' => '',
                        'req' => '',
                        'min' => '',
                        'type' => 'text',
                        'std' => ''),
				*/

                array(  'name' => __( 'Tracking Code', APP_TD ),
                        'desc' => sprintf( '%s' . __( "Sign up for a free <a target='_new' href='%s'>Google Analytics account</a>.", APP_TD ), '<div class="googleico"></div>', 'http://www.google.com/analytics/' ),
                        'tip' => __( 'Paste your analytics tracking code here. Google Analytics is free and the most popular but you can use other providers as well.', APP_TD ),
                        'id' => $app_abbr.'_google_analytics',
                        'css' => 'width:500px;height:150px;',
                        'vis' => '',
                        'req' => '',
                        'min' => '',
                        'type' => 'textarea',
                        'std' => ''),


						array(	'name' => __( 'Pricing Options', APP_TD ),
										'type' => 'title',
										'desc' => '',
										'id' => ''),

								array(  'name' => __( 'Charge for Coupons', APP_TD ),
												'desc' => '',
												'tip' => __( 'This option activates the payment system so you can start charging for coupons on your site.', APP_TD ),
												'id' => $app_abbr.'_charge_coupons',
												'css' => 'min-width:100px;',
												'std' => '',
												'vis' => '',
												'req' => '',
												'js' => '',
												'min' => '',
												'type' => 'select',
												'options' => array( 'yes' => __( 'Yes', APP_TD ),
																						'no'  => __( 'No', APP_TD ) )),

								array(  'name' => __( 'Coupon Price', APP_TD ),
												'desc' => __( 'Only enter numeric values or decimal points. Do not include a currency symbol or commas.', APP_TD ),
												'tip' => __( 'This is the amount you will charge visitors to post a coupon on your site.', APP_TD ),
												'id' => $app_abbr.'_coupon_price',
												'css' => 'width:50px;',
												'vis' => '',
												'type' => 'text',
												'req' => '',
												'min' => '',
												'std' => ''),

								array(  'name' => __( 'Payments Settings', APP_TD ),
												'desc' => sprintf( __( 'Set your currency and Payment Gateway settings in the <a href="%s">Payments Menu.</a>', APP_TD ), 'admin.php?page=app-payments-settings' ),
												'tip' => __( 'Manage Payments Settings including currencies, enable/disable available payment gateways, and manage individual payment gateway\'s settings.', APP_TD ),
												'id' => '',
												'css' => '',
												'vis' => '',
												'type' => 'info',
												'req' => '',
												'min' => '',
												'std' => ''),


            array(	'name' => __( 'General Options', APP_TD ),
                    'type' => 'title',
                    'desc' => '',
                    'id' => ''),

                array(  'name' => __( 'Moderate New Coupons', APP_TD ),
                        'desc' => '',
                        'tip' => __( 'This options allows you to control if new coupons should be manually approved before they go live.', APP_TD ),
                        'id' => $app_abbr.'_coupons_require_moderation',
                        'css' => 'min-width:100px;',
                        'std' => '',
                        'vis' => '',
                        'req' => '',
                        'js' => '',
                        'min' => '',
                        'type' => 'select',
                        'options' => array(  'yes' => __( 'Yes', APP_TD ),
                                             'no'  => __( 'No', APP_TD ) )),

            		array(  'name' => __( 'Prune Expired Coupons', APP_TD ),
                				'desc' => '',
                				'tip' => __( 'A cron job runs once a day and automatically removes all expired coupons from your site (does not delete them, just changes the post status to draft). If no is selected, the coupon will remain live on your site, marked as expired, and moved under the "unreliable coupons" section.', APP_TD ),
                				'id' => $app_abbr.'_prune_coupons',
                				'css' => 'min-width:100px;',
                				'std' => 'no',
                				'vis' => '',
                				'req' => '',
                				'js' => '',
                				'min' => '',
                				'type' => 'select',
                				'options' => array(  'yes' => __( 'Yes', APP_TD ),
                            						     'no'  => __( 'No', APP_TD ) )),

        				array(  'name' => __( 'Moderate New Stores', APP_TD ),
                        'desc' => '',
                        'tip' => __( 'This options allows you to control if new stores submitted with coupons should be manually approved before they go live. Note: Moderate New Coupons must be set to &quot;Yes&quot; for this to work.', APP_TD ),
                        'id' => $app_abbr.'_stores_require_moderation',
                        'css' => 'min-width:100px;',
                        'std' => '',
                        'vis' => '',
                        'req' => '',
                        'js' => '',
                        'min' => '',
                        'type' => 'select',
                        'options' => array(  'yes' => __( 'Yes', APP_TD ),
                                             'no'  => __( 'No', APP_TD ) )),

        				array(  'name' => __( 'Require Registration', APP_TD ),
                        'desc' => '',
                        'tip' => __( 'Anyone submitting a coupon must first have a user account and be logged in. Note: If "Charge for coupons" option is enabled, disabling this option will not take effect.', APP_TD ),
                        'id' => $app_abbr.'_reg_required',
                        'css' => 'min-width:100px;',
                        'std' => '',
                        'vis' => '',
                        'req' => '',
                        'js' => '',
                        'min' => '',
                        'type' => 'select',
                        'options' => array(  'yes' => __( 'Yes', APP_TD ),
                                             'no'  => __( 'No', APP_TD ) )),


        				array(  'name' => __( 'Allow Coupon Editing', APP_TD ),
                        'desc' => '',
                        'tip' => __( 'Allows the coupon owner to edit and republish their existing coupons from their dashboard.', APP_TD ),
                        'id' => $app_abbr.'_coupon_edit',
                        'css' => 'min-width:100px;',
                        'std' => '',
                        'vis' => '',
                        'req' => '',
                        'js' => '',
                        'min' => '',
                        'type' => 'select',
                        'options' => array(  'yes' => __( 'Yes', APP_TD ),
                                             'no'  => __( 'No', APP_TD ) )),

								array(  'name' => __( 'Hide Coupon Code', APP_TD ),
												'desc' => '',
												'tip' => __( 'Allows you to hide coupon codes on site, visitors will see the code only after clicking coupon link bar.', APP_TD ),
												'id' => $app_abbr.'_coupon_code_hide',
												'css' => 'min-width:100px;',
												'std' => '',
												'vis' => '',
												'req' => '',
												'js' => '',
												'min' => '',
												'type' => 'select',
												'options' => array( 'yes' => __( 'Yes', APP_TD ),
																						'no'  => __( 'No', APP_TD ) )),

								array(  'name' => __( 'Allow HTML', APP_TD ),
												'desc' => sprintf( __( "The WordPress <a href='%s'>auto-embeds</a> option must be unchecked to completely disable HTML (YouTube, Flickr, etc).", APP_TD ), 'options-media.php' ),
												'tip' => __( 'Turns on the TinyMCE editor on text area fields and allows the coupon owner to use html markup. Other fields do not allow html by default.', APP_TD ),
												'id' => $app_abbr.'_allow_html',
												'css' => 'min-width:100px;',
												'std' => '',
												'vis' => '',
												'req' => '',
												'js' => '',
												'min' => '',
												'type' => 'select',
												'options' => array(  'yes' => __( 'Yes', APP_TD ),
																							'no'  => __( 'No', APP_TD ) )),

        				array(  'name' => __( 'Show Views Counter', APP_TD ),
                        'desc' => '',
                        'tip' => __( "This will show a 'total views' and 'today's views' at the bottom of each coupon and blog post.", APP_TD ),
                        'id' => $app_abbr.'_stats_all',
                        'css' => 'min-width:100px;',
                        'std' => '',
                        'vis' => '',
                        'req' => '',
                        'js' => '',
                        'min' => '',
                        'type' => 'select',
                        'options' => array(  'yes' => __( 'Yes', APP_TD ),
                                             'no'  => __( 'No', APP_TD ) )),


				// array(  'name' => __( 'Default No Image', APP_TD ),
						// 'desc' => __( 'Upload an image or paste an image URL directly.', APP_TD ),
						// 'tip' => __( 'The full url path to the default no image. If blank, it will use the default theme image.', APP_TD ),
						// 'id' => $app_abbr.'_no_image',
						// 'css' => 'min-width:398px;',
						// 'std' => '',
						// 'vis' => '',
						// 'req' => '',
						// 'js' => '',
						// 'min' => '',
						// 'type' => 'upload'),


                array(  'name' => __( 'Allowed File Types', APP_TD ),
                        'desc' => '',
                        'tip' => __( 'When submitting a printable coupon, only allow these file types to be uploaded (i.e. png,gif,jpg). Comma separated, no spaces.', APP_TD ),
                        'id' => $app_abbr.'_submit_file_types',
                        'css' => 'min-width:250px;',
                        'std' => 'png,gif,jpg,jpeg',
                        'vis' => '',
                        'req' => '',
                        'js' => '',
                        'min' => '',
                        'type' => 'text'),

								array(  'name' => __( 'Form Validation Language', APP_TD ),
												'desc' => __( 'Leave this value blank if your site is in English.', APP_TD ),
												'tip' => __( 'This option allows you to set the language your coupon submission form error messages are displayed in. Enter your two-letter country code (i.e. for German enter de). Not all languages have been translated but you can always add your own. To see the available languages, look in your /clipper/includes/js/validate/localization folder.', APP_TD ),
												'id' => $app_abbr.'_form_val_lang',
												'css' => 'width:75px;',
												'vis' => '',
												'req' => '',
												'min' => '',
												'type' => 'text',
												'std' => ''),

            array(	'name' => __( 'Search Settings', APP_TD ),
                		'type' => 'title',
                    'desc' => '',
                		'id' => ''),

        				array(  'name' => __( 'Enable Search Stats', APP_TD ),
                        'desc' => '',
                        'tip' => __( 'Set this option to yes if you want to record all searches and results found on your website.', APP_TD ),
                        'id' => $app_abbr.'_search_stats',
                        'css' => 'min-width:100px;',
                        'std' => '',
                        'vis' => '',
                        'req' => '',
                        'js' => '',
                        'min' => '',
                        'type' => 'select',
                        'options' => array(  'yes' => __( 'Yes', APP_TD ),
                                             'no'  => __( 'No', APP_TD ) )),

                array(  'name' => __( 'Exclude Pages', APP_TD ),
                        'desc' => '',
                        'tip' => __( 'Set this option to yes if you do not want your pages to show up in your website search results.', APP_TD ),
                        'id' => $app_abbr.'_search_ex_pages',
                        'css' => 'min-width:100px;',
                        'std' => '',
                        'vis' => '',
                        'req' => '',
                        'js' => '',
                        'min' => '',
                        'type' => 'select',
                        'options' => array(  'yes' => __( 'Yes', APP_TD ),
                                             'no'  => __( 'No', APP_TD ) )),

                array(  'name' => __( 'Exclude Blog Posts', APP_TD ),
                        'desc' => '',
                        'tip' => __( 'Set this option to yes if you do not want your blog posts to show up in your website search results.', APP_TD ),
                        'id' => $app_abbr.'_search_ex_blog',
                        'css' => 'min-width:100px;',
                        'std' => '',
                        'vis' => '',
                        'req' => '',
                        'js' => '',
                        'min' => '',
                        'type' => 'select',
                        'options' => array(  'yes' => __( 'Yes', APP_TD ),
                                             'no'  => __( 'No', APP_TD ) )),



    array(  'type' => 'tabend', 'id' => '0'),


    array(  'type' => 'tab',
            'tabname' => __( 'Security/Reports', APP_TD ),
            'id' => '1' ),

            array(	'name' => __( 'Security Settings', APP_TD ),
                    'type' => 'title',
                    'desc' => '',
                    'id' => ''),

                array(  'name' => __( 'Back Office Access', APP_TD ),
                        'desc' => sprintf( __( "View the WordPress <a target='_new' href='%s'>Roles and Capabilities</a> for more information.", APP_TD ), 'http://codex.wordpress.org/Roles_and_Capabilities' ),
                        'tip' => __( 'Allows you to restrict access to the WordPress Back Office (wp-admin) by specific role. Keeping this set to admins only is recommended. Select Disable if you have problems with this feature.', APP_TD ),
                        'id' => $app_abbr.'_admin_security',
                        'css' => 'min-width:100px;',
                        'std' => '',
                        'vis' => '',
                        'req' => '',
                        'js' => '',
                        'min' => '',
                        'type' => 'select',
                        'options' => array(  'manage_options' => __( 'Admins Only', APP_TD ),
                                             'edit_others_posts' => __( 'Admins, Editors', APP_TD ),
                                             'publish_posts' => __( 'Admins, Editors, Authors', APP_TD ),
                                             'edit_posts' => __( 'Admins, Editors, Authors, Contributors', APP_TD ),
                                             'read' => __( 'All Access', APP_TD ),
                                             'disable' => __( 'Disable', APP_TD ) )),





            array(  'name' => __( 'reCaptcha Settings', APP_TD ),
                    'type' => 'title',
                    'desc' => '',
                    'id' => ''),


                array(  'name' => __( 'Enable reCaptcha', APP_TD ),
                        'desc' => sprintf( __( "reCaptcha is a free anti-spam service provided by Google. Learn more about <a target='_new' href='%s'>reCaptcha</a>.", APP_TD ), 'http://code.google.com/apis/recaptcha/' ),
                        'tip' => __( 'Set this option to yes to enable the reCaptcha service that will protect your site against spam registrations. It will show a verification box on your registration page that requires a human to read and enter the words.', APP_TD ),
                        'id' => $app_abbr.'_captcha_enable',
                        'css' => 'width:100px;',
                        'vis' => '',
                        'req' => '',
                        'js' => '',
                        'min' => '',
                        'std' => '',
                        'type' => 'select',
                        'options' => array(  'yes' => __( 'Yes', APP_TD ),
                                             'no'  => __( 'No', APP_TD ) )),

                array(  'name' => __( 'reCaptcha Public Key', APP_TD ),
                        'desc' => sprintf( '%s' . __( "Sign up for a free <a target='_new' href='%s'>Google reCaptcha</a> account.", APP_TD ), '<div class="captchaico"></div>', 'https://www.google.com/recaptcha/admin/create' ),
                        'tip' => __( 'Enter your public key here to enable an anti-spam service on your new user registration page (requires a free Google reCaptcha account). Leave it blank if you do not wish to use this anti-spam feature.', APP_TD ),
                        'id' => $app_abbr.'_captcha_public_key',
                        'css' => 'min-width:500px;',
                        'vis' => '',
                        'req' => '',
                        'min' => '',
                        'type' => 'text',
                        'std' => ''),

                array(  'name' => __( 'reCaptcha Private Key', APP_TD ),
                        'desc' => sprintf( '%s' . __( "Sign up for a free <a target='_new' href='%s'>Google reCaptcha</a> account.", APP_TD ), '<div class="captchaico"></div>', 'https://www.google.com/recaptcha/admin/create' ),
                        'tip' => __( 'Enter your private key here to enable an anti-spam service on your new user registration page (requires a free Google reCaptcha account). Leave it blank if you do not wish to use this anti-spam feature.', APP_TD ),
                        'id' => $app_abbr.'_captcha_private_key',
                        'css' => 'min-width:500px;',
                        'vis' => '',
                        'req' => '',
                        'min' => '',
                        'type' => 'text',
                        'std' => ''),

                array(  'name' => __( 'Choose Theme', APP_TD ),
                        'desc' => '',
                        'tip' => __( 'Select the color scheme you wish to use for reCaptcha.', APP_TD ),
                        'id' => $app_abbr.'_captcha_theme',
                        'css' => 'width:100px;',
                        'vis' => '',
                        'req' => '',
                        'js' => '',
                        'min' => '',
                        'std' => '',
                        'type' => 'select',
                        'options' => array(  'red' => __( 'Red', APP_TD ),
                                             'white' => __( 'White', APP_TD ),
                                             'blackglass' => __( 'Black', APP_TD ),
                                             'clean'  => __( 'Clean', APP_TD ) )),


            array(  'name' => __( 'Report Coupon Settings', APP_TD ),
                    'type' => 'title',
                    'desc' => '',
                    'id' => ''),


                array(  'name' => __( 'Report Select Options', APP_TD ),
                        'desc' => __( 'Options for the reports select field. One per line.', APP_TD ),
                        'tip' => __( 'Enter the different options you want available for the coupon report a problem. Enter one per line.', APP_TD ),
                        'id' => $app_abbr.'_rp_options',
                        'css' => 'min-width:500px;',
                        'vis' => '',
                        'req' => '',
                        'min' => '',
                        'type' => 'report_options',
                        'std' => ''),

                array(  'name' => __( 'Report Coupon Link Text', APP_TD ),
                        'desc' => '',
                        'tip' => __( 'The text to appear as the link for the report feature.', APP_TD ),
                        'id' => $app_abbr.'_rp_display_text',
                        'css' => 'width:250px;',
                        'vis' => '',
                        'req' => '',
                        'min' => '',
                        'type' => 'text',
                        'std' => ''),

                array(  'name' => __( 'Registered Users Only', APP_TD ),
                        'desc' => __( 'Only allow registered users to report problems.', APP_TD ),
                        'tip' => __( 'Select yes to only allow registered users to submit problem reports', APP_TD ),
                        'id' => $app_abbr.'_rp_registeronly',
						            'css' => 'width:100px;',
                        'vis' => '',
                        'req' => '',
                        'js' => '',
                        'min' => '',
                        'std' => '0',
                        'type' => 'select',
                        'options' => array('0' => __( 'No', APP_TD ),
                                           '1' => __( 'Yes', APP_TD ) )),

            array(	'name' => __( 'Report Votes Settings', APP_TD ),
                    'type' => 'title',
                    'desc' => '',
                    'id' => ''),

                array(  'name' => __( 'Reset Votes', APP_TD ),
                        'desc' => __( 'Reset the vote count for all coupons.', APP_TD ),
                        'tip' => __( 'Select yes to reset the vote count for all coupons.', APP_TD ),
                        'id' => $app_abbr.'_votes_reset_count',
                        'css' => 'width:100px;',
                        'vis' => '',
                        'req' => '',
                        'js' => '',
                        'min' => '',
                        'std' => '',
                        'type' => 'select',
                        'options' => array('0' => __( 'No', APP_TD ),
                                           '1' => __( 'Yes', APP_TD ) )),

    array(  'type' => 'tabend', 'id' => '1'),


    array(  'type' => 'tab',
            'tabname' => __( 'Advertising', APP_TD ),
            'id' => '2' ),

            array(	'name' => __( 'Ad (336x280)', APP_TD ),
                    'type' => 'title',
                    'desc' => '',
                    'id' => ''),

                array(  'name' => __( 'Enable Ad', APP_TD ),
                        'desc' => '',
                        'tip' => __( 'Set this option to no if you do not wish to have a 336x280 ads displayed on the individual blog posts and store pages.', APP_TD ),
                        'id' => $app_abbr.'_adcode_336x280_enable',
                        'css' => 'width:100px;',
                        'vis' => '',
                        'req' => '',
                        'js' => '',
                        'min' => '',
                        'std' => '',
                        'type' => 'select',
                        'options' => array(  'yes' => __( 'Yes', APP_TD ),
                                             'no'  => __( 'No', APP_TD ) )),

                array(  'name' => __( 'Ad Code', APP_TD ),
                        'desc' => sprintf( __( "Paste in your <a target='_new' href='%s'>Google AdSense</a> code here.", APP_TD ), 'http://www.google.com/adsense/' ),
                        'tip' => __( 'You may use html and/or javascript code provided by Google AdSense.', APP_TD ),
                        'id' => $app_abbr.'_adcode_336x280',
                        'css' => 'width:500px;height:200px;',
                        'std' => '',
                        'vis' => '',
                        'req' => '',
                        'min' => '',
                        'type' => 'textarea',
                        'std' => ''),

                array(  'name' => __( 'Ad Image URL', APP_TD ),
						            'desc' => __( 'Upload your ad creative or paste the ad image URL directly.', APP_TD ),
                        'tip' => __( 'If you would rather use an image ad instead of code provided by Google AdSense, use this instead.', APP_TD ),
                        'id' => $app_abbr.'_adcode_336x280_url',
                        'css' => 'min-width:398px;',
                        'vis' => '',
                        'req' => '',
                        'min' => '',
                        'type' => 'upload',
                        'std' => ''),

                array(  'name' => __( 'Ad Destination', APP_TD ),
                        'desc' => __( 'Paste the destination URL of your custom logo here. (i.e. http://www.yoursite.com/landing-page.html)', APP_TD ),
                        'tip' => __( 'When a visitor clicks on your ad image, this is the destination they will be sent to.', APP_TD ),
                        'id' => $app_abbr.'_adcode_336x280_dest',
                        'css' => 'min-width:500px;',
                        'vis' => '',
                        'req' => '',
                        'min' => '',
                        'type' => 'text',
                        'std' => ''),


    array(  'type' => 'tabend', 'id' => '2'),


    array(  'type' => 'tab',
            'tabname' => __( 'Advanced', APP_TD ),
            'id' => '3' ),

            array(	'name' => __( 'Advanced Options', APP_TD ),
                    'type' => 'title',
                    'desc' => '',
                    'id' => ''),

                array(  'name' => __( 'Disable Core Stylesheets', APP_TD ),
                        'desc' => '',
                        'tip' => __( 'If you are interested in creating a child theme or just want to completely disable the core Clipper styles, change this option to yes. (Note: this option is for advanced users. Do not change unless you know what you are doing.)', APP_TD ),
                        'id' => $app_abbr.'_disable_stylesheet',
                        'css' => 'width:100px;',
                        'std' => '',
                        'vis' => '',
                        'req' => '',
                        'js' => '',
                        'min' => '',
                        'type' => 'select',
                        'options' => array(  'no'   => __( 'No', APP_TD ),
                                             'yes'  => __( 'Yes', APP_TD ) )),

                array(  'name' => __( 'Enable Debug Mode', APP_TD ),
                        'desc' => '',
                        'tip' => __( "This will print out the query_vars and queries arrays (if <code>define('SAVEQUERIES', true);</code> is added to your wp-config.php) in the footer of your website. This should be used for debugging and will only be visible to logged in admins.", APP_TD ),
                        'id' => $app_abbr.'_debug_mode',
                        'css' => 'width:100px;',
                        'std' => '',
                        'vis' => '',
                        'req' => '',
                        'js' => '',
                        'min' => '',
                        'type' => 'select',
                        'options' => array(  'no'   => __( 'No', APP_TD ),
                                             'yes'  => __( 'Yes', APP_TD ) )),


                array(  'name' => __( 'Use Google CDN jQuery', APP_TD ),
                        'desc' => '',
                        'tip' => __( "This will use Google's hosted jQuery files which are served from their global content delivery network. This will help your site load faster and save bandwidth.", APP_TD ),
                        'id' => $app_abbr.'_google_jquery',
                        'css' => 'width:100px;',
                        'std' => '',
                        'vis' => '',
                        'req' => '',
                        'js' => '',
                        'min' => '',
                        'type' => 'select',
                        'options' => array(  'no'   => __( 'No', APP_TD ),
                                             'yes'  => __( 'Yes', APP_TD ) )),

								array(  'name' => __( 'Disable WordPress Login Page', APP_TD ),
												'desc' => '',
												'tip' => __( 'If someone tries to access <code>wp-login.php</code> directly, they will be redirected to Clipper themed login pages. If you want to use any "maintenance mode" plugins, you should enable the default WordPress login page.', APP_TD ),
												'id' => $app_abbr.'_disable_wp_login',
												'css' => 'width:100px;',
												'std' => '',
												'vis' => '',
												'req' => '',
												'js' => '',
												'min' => '',
												'type' => 'select',
												'options' => array( 'no'  => __( 'No', APP_TD ),
																						'yes' => __( 'Yes', APP_TD ) )),

                array(  'name' => __( 'Disable WordPress Version Meta Tag', APP_TD ),
                        'desc' => '',
                        'tip' => __( "This will remove the WordPress generator meta tag in the source code of your site <code>< meta name='generator' content='WordPress 3.1' ></code>. It's an added security measure which prevents anyone from seeing what version of WordPress you are using. It also helps to deter hackers from taking advantage of vulnerabilities sometimes present in WordPress. (Yes is recommended)", APP_TD ),
                        'id' => $app_abbr.'_remove_wp_generator',
                        'css' => 'width:100px;',
                        'std' => '',
                        'vis' => '',
                        'req' => '',
                        'js' => '',
                        'min' => '',
                        'type' => 'select',
                        'options' => array(  'no'   => __( 'No', APP_TD ),
                                             'yes'  => __( 'Yes', APP_TD ) )),

                array(  'name' => __( 'Disable WordPress User Toolbar', APP_TD ),
                        'desc' => '',
                        'tip' => __( "This will remove the WordPress user toolbar at the top of your web site which is displayed for all logged in users. This feature was added in WordPress 3.1.", APP_TD ),
                        'id' => $app_abbr.'_remove_admin_bar',
                        'css' => 'width:100px;',
                        'std' => '',
                        'vis' => '',
                        'req' => '',
                        'js' => '',
                        'min' => '',
                        'type' => 'select',
                        'options' => array(  'no'   => __( 'No', APP_TD ),
                                             'yes'  => __( 'Yes', APP_TD ) )),


            array(  'name' => __( 'Custom Post Type & Taxonomy URLs', APP_TD ),
                    'type' => 'title',
                    'desc' => '',
                    'id' => ''),

                array(  'name' => __( 'Coupon Listing Base URL', APP_TD ),
                        'desc'=> sprintf( __( "IMPORTANT: You must <a target='_blank' href='%s'>re-save your permalinks</a> for this change to take effect.", APP_TD ), 'options-permalink.php' ),
                        'tip' => __( 'This controls the base name of your coupon listing urls. The default is coupon and will look like this: http://www.yoursite.com/jobs/ad-title-here/. Do not include any slashes. This should only be alpha and/or numeric values. You should not change this value once you have launched your site otherwise you risk breaking urls of other sites pointing to yours, etc.', APP_TD ),
                        'id' => $app_abbr.'_coupon_permalink',
                        'css' => 'width:250px;',
                        'type' => 'text',
                        'req' => '',
                        'min' => '',
                        'std' => '',
                        'vis' => '',
                        'visid' => ''),

                array(  'name' => __( 'Coupon Category Base URL', APP_TD ),
                        'desc'=> sprintf( __( "IMPORTANT: You must <a target='_blank' href='%s'>re-save your permalinks</a> for this change to take effect.", APP_TD ), 'options-permalink.php' ),
                        'tip' => __( 'This controls the base name of your coupon category urls. The default is coupon-category and will look like this: http://www.yoursite.com/coupon-category/category-name/. Do not include any slashes. This should only be alpha and/or numeric values. You should not change this value once you have launched your site otherwise you risk breaking urls of other sites pointing to yours, etc.', APP_TD ),
                        'id' => $app_abbr.'_coupon_cat_tax_permalink',
                        'css' => 'width:250px;',
                        'type' => 'text',
                        'req' => '',
                        'min' => '',
                        'std' => '',
                        'vis' => '',
                        'visid' => ''),

                array(  'name' => __( 'Coupon Store Base URL', APP_TD ),
                        'desc'=> sprintf( __( "IMPORTANT: You must <a target='_blank' href='%s'>re-save your permalinks</a> for this change to take effect.", APP_TD ), 'options-permalink.php' ),
                        'tip' => __( 'This controls the base name of your coupon store urls. The default is store and will look like this: http://www.yoursite.com/store/store-name/. Do not include any slashes. This should only be alpha and/or numeric values. You should not change this value once you have launched your site otherwise you risk breaking urls of other sites pointing to yours, etc.', APP_TD ),
                        'id' => $app_abbr.'_coupon_store_tax_permalink',
                        'css' => 'width:250px;',
                        'type' => 'text',
                        'req' => '',
                        'min' => '',
                        'std' => '',
                        'vis' => '',
                        'visid' => ''),

                array(  'name' => __( 'Coupon Type Base URL', APP_TD ),
                        'desc'=> sprintf( __( "IMPORTANT: You must <a target='_blank' href='%s'>re-save your permalinks</a> for this change to take effect.", APP_TD ), 'options-permalink.php' ),
                        'tip' => __( 'This controls the base name of your coupon type urls. The default is coupon-type and will look like this: http://www.yoursite.com/coupon-type/tag-name/. Do not include any slashes. This should only be alpha and/or numeric values. You should not change this value once you have launched your site otherwise you risk breaking urls of other sites pointing to yours, etc.', APP_TD ),
                        'id' => $app_abbr.'_coupon_type_tax_permalink',
                        'css' => 'width:250px;',
                        'type' => 'text',
                        'req' => '',
                        'min' => '',
                        'std' => '',
                        'vis' => '',
                        'visid' => ''),

                array(  'name' => __( 'Coupon Tag Base URL', APP_TD ),
                        'desc'=> sprintf( __( "IMPORTANT: You must <a target='_blank' href='%s'>re-save your permalinks</a> for this change to take effect.", APP_TD ), 'options-permalink.php' ),
                        'tip' => __( 'This controls the base name of your coupon tag urls. The default is coupon-tag and will look like this: http://www.yoursite.com/coupon-tag/tag-name/. Do not include any slashes. This should only be alpha and/or numeric values. You should not change this value once you have launched your site otherwise you risk breaking urls of other sites pointing to yours, etc.', APP_TD ),
                        'id' => $app_abbr.'_coupon_tag_tax_permalink',
                        'css' => 'width:250px;',
                        'type' => 'text',
                        'req' => '',
                        'min' => '',
                        'std' => '',
                        'vis' => '',
                        'visid' => ''),


            array(  'name' => __( 'Store &amp; Coupon Redirect URLs', APP_TD ),
                    'type' => 'title',
                    'desc' => '',
                    'id' => ''),

                array(  'name' => __( 'Coupon Redirect Base URL', APP_TD ),
                        'desc'=> sprintf( __( "IMPORTANT: This value must be unique (not like any other base/path URLs).<br /> You must also <a target='_blank' href='%s'>re-save your permalinks</a> for this change to take effect.", APP_TD ), 'options-permalink.php' ),
                        'tip' => __( 'This controls the base name of your display url. If you have a destination url setup for a coupon, it will look something like this when you hover over the link: http://www.yoursite.com/go/coupon-name/23. The &quot;/go/&quot; is what is controlled here. Only enter alpha characters (no slashes, etc).', APP_TD ),
                        'id' => $app_abbr.'_coupon_redirect_base_url',
                        'css' => 'width:250px;',
                        'type' => 'text',
                        'req' => '',
                        'min' => '',
                        'std' => '',
                        'vis' => '',
                        'visid' => ''),

                array(  'name' => __( 'Store Redirect Base URL', APP_TD ),
                        'desc'=> sprintf( __( "IMPORTANT: This value must be unique (not like any other base/path URLs).<br /> You must also <a target='_blank' href='%s'>re-save your permalinks</a> for this change to take effect.", APP_TD ), 'options-permalink.php' ),
                        'tip' => __( 'This controls the base name of your display url. If you have a destination url setup for a store, it will look something like this when you hover over the link: http://www.yoursite.com/go-store/store-name/23. The &quot;/go-store/&quot; is what is controlled here. Only enter alpha characters (no slashes, etc).', APP_TD ),
                        'id' => $app_abbr.'_store_redirect_base_url',
                        'css' => 'width:250px;',
                        'type' => 'text',
                        'req' => '',
                        'min' => '',
                        'std' => '',
                        'vis' => '',
                        'visid' => ''),


    array(  'type' => 'tabend', 'id' => '3'),


);




$options_emails = array (


    array(  'type' => 'tab',
            'tabname' => __( 'General', APP_TD ),
            'id' => '0' ),

            array(	'name' => __( 'Email Notifications', APP_TD ),
                    'desc' => sprintf( __( "Emails will be sent to: %s (<a target='_new' href='%s'>Change email address</a>)", APP_TD ), get_option('admin_email'), 'options-general.php' ),
                    'type' => 'title',
                    'id' => ''),

                array(  'name' => __( 'New Coupon Email', APP_TD ),
                        'desc' => '',
                        'tip' => __( 'Send the site admin an email once a new coupon has been submitted.', APP_TD ),
                        'id' => $app_abbr.'_new_ad_email',
                        'css' => 'width:100px;',
                        'std' => '',
                        'vis' => '',
                        'req' => '',
                        'js' => '',
                        'min' => '',
                        'type' => 'select',
                        'options' => array(  'yes' => __( 'Yes', APP_TD ),
                                             'no'  => __( 'No', APP_TD ) )),

                array(  'name' => __( 'Send Report Email', APP_TD ),
                        'desc' => '',
                        'tip' => __( 'Send the site admin an email when a problem has been reported on a coupon.', APP_TD ),
                        'id' => $app_abbr.'_rp_send_email',
                        'css' => 'width:100px;',
                        'vis' => '',
                        'req' => '',
                        'js' => '',
                        'min' => '',
                        'std' => 1,
                        'type' => 'select',
                        'options' => array('0' => __( 'No', APP_TD ),
                                            '1' => __( 'Yes', APP_TD ) )),

                array(  'name' => __( 'Prune Coupons Email', APP_TD ),
                        'desc' => '',
                        'tip' => __( 'Send me an email every time the system prunes expired coupons.', APP_TD ),
                        'id' => $app_abbr.'_prune_coupons_email',
                        'css' => 'width:100px;',
                        'std' => '',
                        'vis' => '',
                        'req' => '',
                        'js' => '',
                        'min' => '',
                        'type' => 'select',
                        'options' => array(  'no'   => __( 'No', APP_TD ),
                                             'yes'  => __( 'Yes', APP_TD ) )),

    array(  'type' => 'tabend', 'id' => '0'),


    array(  'type' => 'tab',
            'tabname' => __( 'New User', APP_TD ),
            'id' => '1' ),

            array(	'name' => __( 'New User Registration Email', APP_TD ),
                    'type' => 'title',
                    'desc' => '',
                    'id' => ''),

                array(  'name' => __( 'Enable Custom Email', APP_TD ),
                        'desc' => '',
                        'tip' => __( 'Sends a custom new user notification email to your customers by using the fields you complete below. If this is set to &quot;No&quot;, the default WordPress new user notification email will be sent. This is useful for debugging if your custom emails are not being sent.', APP_TD ),
                        'id' => $app_abbr.'_nu_custom_email',
                        'css' => 'width:100px;',
                        'std' => '',
                        'vis' => '',
                        'req' => '',
                        'js' => '',
                        'min' => '',
                        'type' => 'select',
                        'options' => array(  'yes' => __( 'Yes', APP_TD ),
                                             'no'  => __( 'No', APP_TD ) )),

                array(  'name' => __( 'From Name', APP_TD ),
                        'desc' => '',
                        'tip' => __( 'This is what your customers will see as the &quot;from&quot; when they receive the new user registration email. Use plain text only', APP_TD ),
                        'id' => $app_abbr.'_nu_from_name',
                        'css' => 'width:250px;',
                        'vis' => '',
                        'type' => 'text',
                        'req' => '',
                        'min' => '',
                        'std' => ''),

                array(  'name' => __( 'From Email', APP_TD ),
                        'desc' => '',
                        'tip' => __( 'This is what your customers will see as the &quot;from&quot; email address (also the reply to) when they receive the new user registration email. Use only a valid and existing email address with no html or variables.', APP_TD ),
                        'id' => $app_abbr.'_nu_from_email',
                        'css' => 'width:250px;',
                        'vis' => '',
                        'type' => 'text',
                        'req' => '',
                        'min' => '',
                        'std' => ''),

                array(  'name' => __( 'Email Subject', APP_TD ),
                        'desc' => '',
                        'tip' => __( 'This is the subject line your customers will see when they receive the new user registration email. Use text and variables only.', APP_TD ),
                        'id' => $app_abbr.'_nu_email_subject',
                        'css' => 'width:400px;',
                        'vis' => '',
                        'type' => 'text',
                        'req' => '',
                        'min' => '',
                        'std' => ''),

                array(  'name' => __( 'Allow HTML in Body', APP_TD ),
                        'desc' => '',
                        'tip' => __( 'This option allows you to use html markup in the email body below. It is recommended to keep it set to &quot;No&quot; to avoid problems with delivery. If you turn it on, make sure to test it and make sure the formatting looks ok and gets delivered properly.', APP_TD ),
                        'id' => $app_abbr.'_nu_email_type',
                        'css' => 'width:100px;',
                        'vis' => '',
                        'std' => '',
                        'js' => '',
                        'type' => 'select',
                        'options' => array(  'text/HTML'   => __( 'Yes', APP_TD ),
                                             'text/plain'  => __( 'No', APP_TD ) )),

                array(  'name' => __( 'Email Body', APP_TD ),
                        'desc' => __( 'You may use the following variables within the email body and/or subject line.<br/><br/><strong>%username%</strong> - prints out the username<br/><strong>%useremail%</strong> - prints out the users email address<br/><strong>%password%</strong> - prints out the users text password<br/><strong>%siteurl%</strong> - prints out your website url<br/><strong>%blogname%</strong> - prints out your site name<br/><strong>%loginurl%</strong> - prints out your sites login url<br/><br/><br/><br/>Each variable MUST have the percentage signs wrapped around it with no spaces.<br/>Always test your email after making any changes to make sure it is working & formatted correctly.<br/>If you do not receive an email, chances are something is wrong with your email body.', APP_TD ),
                        'tip' => __( 'Enter the text you would like your customers to see in the new user registration email. Make sure to always at least include the %username% and %password% variables otherwise they might forget later.', APP_TD ),
                        'id' => $app_abbr.'_nu_email_body',
                        'css' => 'width:550px;height:250px;',
                        'vis' => '',
                        'req' => '',
                        'min' => '',
                        'type' => 'textarea',
                        'std' => ''),

    array(  'type' => 'tabend', 'id' => '1'),


    array(  'type' => 'tab',
            'tabname' => __( 'New Coupon', APP_TD ),
            'id' => '2' ),

            array(	'name' => __( 'New Coupon Email', APP_TD ),
                    'desc' => '',
                    'type' => 'title',
                    'id' => ''),

                array(  'name' => __( 'Enable Custom Email', APP_TD ),
                        'desc' => '',
                        'tip' => __( 'Sends a custom email to your customers whenever they submit a new coupon. If you do not require user registration to submit coupons, no email will be sent out.', APP_TD ),
                        'id' => $app_abbr.'_nc_custom_email',
                        'css' => 'width:100px;',
                        'std' => '',
                        'vis' => '',
                        'req' => '',
                        'js' => '',
                        'min' => '',
                        'type' => 'select',
                        'options' => array(  'yes' => __( 'Yes', APP_TD ),
                                             'no'  => __( 'No', APP_TD ) )),

                array(  'name' => __( 'From Name', APP_TD ),
                        'desc' => '',
                        'tip' => __( 'This is what your customers will see as the &quot;from&quot; when they receive the new user registration email. Use plain text only', APP_TD ),
                        'id' => $app_abbr.'_nc_from_name',
                        'css' => 'width:250px;',
                        'vis' => '',
                        'type' => 'text',
                        'req' => '',
                        'min' => '',
                        'std' => ''),

                array(  'name' => __( 'From Email', APP_TD ),
                        'desc' => '',
                        'tip' => __( 'This is what your customers will see as the &quot;from&quot; email address (also the reply to) when they receive this email. Use only a valid and existing email address with no html or variables.', APP_TD ),
                        'id' => $app_abbr.'_nc_from_email',
                        'css' => 'width:250px;',
                        'vis' => '',
                        'type' => 'text',
                        'req' => '',
                        'min' => '',
                        'std' => ''),

                array(  'name' => __( 'Email Subject', APP_TD ),
                        'desc' => '',
                        'tip' => __( 'This is the subject line your customers will see when they receive this email. Use text and variables only.', APP_TD ),
                        'id' => $app_abbr.'_nc_email_subject',
                        'css' => 'width:400px;',
                        'vis' => '',
                        'type' => 'text',
                        'req' => '',
                        'min' => '',
                        'std' => ''),

                array(  'name' => __( 'Allow HTML in Body', APP_TD ),
                        'desc' => '',
                        'tip' => __( 'This option allows you to use html markup in the email body below. It is recommended to keep it set to &quot;No&quot; to avoid problems with delivery. If you turn it on, make sure to test it and make sure the formatting looks ok and gets delivered properly.', APP_TD ),
                        'id' => $app_abbr.'_nc_email_type',
                        'css' => 'width:100px;',
                        'vis' => '',
                        'std' => '',
                        'js' => '',
                        'type' => 'select',
                        'options' => array(  'text/HTML'   => __( 'Yes', APP_TD ),
                                             'text/plain'  => __( 'No', APP_TD ) )),

                array(  'name' => __( 'Email Body', APP_TD ),
                        'desc' => __( 'You may use the following variables within the email body and/or subject line.<br/><br/><strong>%username%</strong> - prints out the username<br/><strong>%useremail%</strong> - prints out the users email address<br/><strong>%siteurl%</strong> - prints out your website url<br/><strong>%blogname%</strong> - prints out your site name<br/><strong>%loginurl%</strong> - prints out your sites login url<br/><strong>%title%</strong> - prints out the coupon title<br/><strong>%code%</strong> - prints out the coupon code<br/><strong>%category%</strong> - prints out the coupon category<br/><strong>%store%</strong> - prints out the coupon store name<br/><strong>%description%</strong> - prints out the coupon description<br/><strong>%dashurl%</strong> - prints out the dashboard url<br/><br/><br/>Each variable MUST have the percentage signs wrapped around it with no spaces.<br/>Always test your email after making any changes to make sure it is working & formatted correctly.<br/>If you do not receive an email, chances are something is wrong with your email body.', APP_TD ),
                        'tip' => __( 'Enter the text you would like your customers to see in this email.', APP_TD ),
                        'id' => $app_abbr.'_nc_email_body',
                        'css' => 'width:550px;height:250px;',
                        'vis' => '',
                        'req' => '',
                        'min' => '',
                        'type' => 'textarea',
                        'std' => ''),

    array(  'type' => 'tabend', 'id' => '2'),

);

?>